# Generated by Django 5.0.1 on 2024-01-31 21:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StockPortfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=20, null=True)),
                ('name', models.CharField(max_length=255, null=True)),
                ('quantity', models.FloatField(default=0, null=True)),
                ('ISIN', models.CharField(max_length=12, unique=True)),
                ('country_code', models.CharField(max_length=4, null=True)),
                ('base_currency_symbol', models.CharField(max_length=4, null=True)),
                ('avg_price', models.FloatField(default=0, null=True)),
                ('last_price', models.FloatField(default=0, null=True)),
                ('all_bought_price', models.FloatField(default=0, null=True)),
                ('all_market_price', models.FloatField(default=0, null=True)),
                ('all_bought_price_in_euro', models.FloatField(default=0, null=True)),
                ('last_price_in_euro', models.FloatField(default=0, null=True)),
                ('avg_price_in_euro', models.FloatField(default=0, null=True)),
                ('all_market_price_in_euro', models.FloatField(default=0, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('deleted_on', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
