# Generated by Django 5.0.1 on 2024-01-31 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=6, verbose_name='Ticker')),
                ('ISIN', models.CharField(max_length=12, unique=True)),
                ('currency', models.CharField(blank='USD', choices=[('USD', 'USD'), ('EUR', 'EUR'), ('SEK', 'SEK'), ('CAD', 'CAD'), ('GBP', 'GBP'), ('AUD', 'AUD'), ('NOK', 'NOK'), ('DKK', 'DKK'), ('HKD', 'HKD')], default='USD', max_length=4, verbose_name='Currency')),
                ('sector', models.CharField(blank='Not set', choices=[('Not set', 'Not set'), ('Energy', 'Energy'), ('Materials', 'Materials'), ('Industrials', 'Industrials'), ('Utilities', 'Utilities'), ('Healthcare', 'Healthcare'), ('Financials', 'Financials'), ('Consumer Discretionary', 'Consumer Discretionary'), ('Consumer Staples', 'Consumer Staples'), ('Information Technology', 'Information Technology'), ('Communication Services', 'Communication Services'), ('Real Estate', 'Real Estate')], default='Not set', max_length=20, verbose_name='Sector')),
            ],
            options={
                'verbose_name': 'stock item',
                'verbose_name_plural': 'stock items',
            },
        ),
        migrations.RemoveField(
            model_name='stockportfolio',
            name='ISIN',
        ),
        migrations.RemoveField(
            model_name='stockportfolio',
            name='all_bought_price',
        ),
        migrations.RemoveField(
            model_name='stockportfolio',
            name='all_bought_price_in_euro',
        ),
        migrations.RemoveField(
            model_name='stockportfolio',
            name='all_market_price',
        ),
        migrations.RemoveField(
            model_name='stockportfolio',
            name='all_market_price_in_euro',
        ),
        migrations.RemoveField(
            model_name='stockportfolio',
            name='avg_price_in_euro',
        ),
        migrations.RemoveField(
            model_name='stockportfolio',
            name='base_currency_symbol',
        ),
        migrations.RemoveField(
            model_name='stockportfolio',
            name='country_code',
        ),
        migrations.RemoveField(
            model_name='stockportfolio',
            name='last_price',
        ),
        migrations.RemoveField(
            model_name='stockportfolio',
            name='last_price_in_euro',
        ),
        migrations.RemoveField(
            model_name='stockportfolio',
            name='symbol',
        ),
        migrations.AddField(
            model_name='stockportfolio',
            name='currency',
            field=models.CharField(max_length=4, null=True, verbose_name='Currency'),
        ),
        migrations.AddField(
            model_name='stockportfolio',
            name='total_price',
            field=models.FloatField(default=0, null=True, verbose_name='Total'),
        ),
        migrations.AlterField(
            model_name='stockportfolio',
            name='avg_price',
            field=models.FloatField(default=0, null=True, verbose_name='Avg price'),
        ),
        migrations.AlterField(
            model_name='stockportfolio',
            name='name',
            field=models.CharField(max_length=100, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='stockportfolio',
            name='quantity',
            field=models.FloatField(default=0, null=True, verbose_name='Quantity'),
        ),
        migrations.AddField(
            model_name='stockportfolio',
            name='ticker',
            field=models.ManyToManyField(to='stocks.stockitem'),
        ),
    ]
