# Generated by Django 5.0.1 on 2024-01-31 23:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0002_stockitem_remove_stockportfolio_isin_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockportfolio',
            name='ticker',
        ),
        migrations.AddField(
            model_name='stockportfolio',
            name='ticker',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='stocks.stockitem'),
        ),
    ]
