# Generated by Django 5.0.1 on 2024-02-01 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0003_remove_stockportfolio_ticker_stockportfolio_ticker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockitem',
            name='ISIN',
            field=models.CharField(max_length=12, null=True, unique=True),
        ),
    ]
